name: create-dev-environment

on: 
  workflow_dispatch:
    inputs:
      env_name:
        description: name for the environment to be created
        required: true
      user_name:
         description: User name
         required: true
      user_pd:
         description: User password
         required: true

env:
  CLIENT_ID: ${{secrets.CLIENT_ID}}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
  TENANT_ID: ${{secrets.TENANT_ID}}
  
jobs:
  create-dev-environment:
#    runs-on: windows-latest
    runs-on: ubuntu-latest
    steps:
      - name: Install PAC CLI
        uses: microsoft/powerplatform-actions/actions-install@v1

      - if: ${{ always() }}
        id: get-pac-path
        name: Add PAC to path
        shell: pwsh
        run: |
          $actionsPath = "${{ runner.temp }}".Replace("_temp","_actions")
          if ($env:RUNNER_OS == 'Linux') {
            $array = Get-ChildItem "/tmp/powerplatform-actions*" -Recurse | Where-Object{$_.FullName.EndsWith('/pac')}
            $pacPath = $array[0].Directory.FullName
          }
          "$pacPath" >> $env:GITHUB_PATH
          
      - name: Setup Authentication, Who-Am-I, and Create Dev Env
        run: |
          # For ubuntu runner, replace "& $env:POWERPLATFORMTOOLS_PACPATH" with "pac"
          #
          # Universal profiles do not currently work well with SPNs. Global Discovery Service is not callable by SPNs, so it cannot retrieve a URL to talk to any dataverse environments.
          # & $env:POWERPLATFORMTOOLS_PACPATH auth create --name "Actions" -id ${{secrets.CLIENT_ID }} -cs ${{ secrets.CLIENT_SECRET }} -t ${{secrets.TENANT_ID }}
          #
          # Must use username/password to create an environment.

          pac auth create --name "Actions" --username ${{ github.event.inputs.user_name }} --password "${{ github.event.inputs.user_pd }}"
          pac org who
          pac admin create `
            --name ${{ github.event.inputs.env_name}} `
            --type "Developer"
