name: apply-tenant-settings

on: workflow_dispatch

jobs:
  apply-tenant-settings:
    runs-on: windows-latest
    steps:
      - name: Install PAC CLI
        uses: microsoft/powerplatform-actions/actions-install@v1

      - if: ${{ always() }}
        id: get-pac-path
        name: Add PAC to path
        shell: pwsh
        run: |
          $actionsPath = "${{ runner.temp }}".Replace("_temp","_actions")
          if ($env:RUNNER_OS -eq "Windows") {
            # $array = Get-ChildItem $actionsPath -Recurse | Where-Object{$_.FullName.EndsWith('pac\tools\pac.exe')}
            $array = Get-ChildItem $actionsPath -Recurse | Where-Object{$_.FullName.EndsWith('\tools\pac.exe')}
            $filePath = $env:POWERPLATFORMTOOLS_PACPATH
            $pacPath = Split-Path -Path $filePath -Parent
            Write-Host "Directory Path: $pacPath"
          }
          else {
            $array = Get-ChildItem $actionsPath -Recurse | Where-Object{$_.FullName.EndsWith('pac_linux/tools/pac')}
          }
          # $pacPath = $env:POWERPLATFORMTOOLS_PACPATH
          # $pacPath = $array[0].Directory.FullName
          "$pacPath" >> $env:GITHUB_PATH

        # We need to add CLIENT_ID, CLIENT_SECRET, and TENANT_ID in secrets
      - name: Setup Authentication
        working-directory: $env:GITHUB_PATH
        run: |
          $env:GITHUB_PATH\pac.exe auth create --name "Actions" -id ${{secrets.CLIENT_ID}} -cs ${{ secrets.CLIENT_SECRET }} -t ${{secrets.TENANT_ID}}
          # $env:GITHUB_PATH auth create --name "Actions" -id ${{secrets.CLIENT_ID}} -cs ${{ secrets.CLIENT_SECRET }} -t ${{secrets.TENANT_ID}}

      - name: Who Am I
        working-directory: $env:GITHUB_PATH      
        run: |
          $env:GITHUB_PATH\pac.exe org who
          # $env:GITHUB_PATH org who
 
